# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.text_result = QtWidgets.QPlainTextEdit(self.tab)
        self.text_result.setGeometry(QtCore.QRect(90, 220, 541, 111))
        self.text_result.setObjectName("text_result")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 71, 17))
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 70, 621, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.chk_report = QtWidgets.QCheckBox(self.frame)
        self.chk_report.setGeometry(QtCore.QRect(10, 10, 141, 23))
        self.chk_report.setObjectName("chk_report")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 601, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_dir_report = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_dir_report.setObjectName("txt_dir_report")
        self.horizontalLayout.addWidget(self.txt_dir_report)
        self.btn_report = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_report.setObjectName("btn_report")
        self.horizontalLayout.addWidget(self.btn_report)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 80, 601, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txt_report_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_report_name.setObjectName("txt_report_name")
        self.horizontalLayout_2.addWidget(self.txt_report_name)
        self.btn_update = QtWidgets.QPushButton(self.tab)
        self.btn_update.setGeometry(QtCore.QRect(480, 380, 137, 25))
        self.btn_update.setObjectName("btn_update")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 611, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txt_cfdi_dir = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_cfdi_dir.setObjectName("txt_cfdi_dir")
        self.horizontalLayout_3.addWidget(self.txt_cfdi_dir)
        self.btn_folder = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_folder.setObjectName("btn_folder")
        self.horizontalLayout_3.addWidget(self.btn_folder)
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.text_result.raise_()
        self.label_4.raise_()
        self.btn_update.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.select_empresa = QtWidgets.QComboBox(self.tab_2)
        self.select_empresa.setGeometry(QtCore.QRect(100, 20, 421, 25))
        self.select_empresa.setObjectName("select_empresa")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 81, 25))
        self.label_5.setObjectName("label_5")
        self.btn_load_empresa = QtWidgets.QPushButton(self.tab_2)
        self.btn_load_empresa.setGeometry(QtCore.QRect(530, 20, 91, 25))
        self.btn_load_empresa.setObjectName("btn_load_empresa")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 70, 621, 281))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tbl_request = QtWidgets.QTableWidget(self.frame_2)
        self.tbl_request.setGeometry(QtCore.QRect(10, 40, 601, 181))
        self.tbl_request.setObjectName("tbl_request")
        self.tbl_request.setColumnCount(7)
        self.tbl_request.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_request.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_request.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_request.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_request.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_request.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_request.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_request.setHorizontalHeaderItem(6, item)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 221, 17))
        self.label_6.setObjectName("label_6")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(180, 240, 254, 27))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_start = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_5.addWidget(self.btn_start)
        self.btn_check = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_check.setObjectName("btn_check")
        self.horizontalLayout_5.addWidget(self.btn_check)
        self.btn_download = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_download.setObjectName("btn_download")
        self.horizontalLayout_5.addWidget(self.btn_download)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(230, 360, 168, 27))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_add_request = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_add_request.setObjectName("btn_add_request")
        self.horizontalLayout_4.addWidget(self.btn_add_request)
        self.btn_delete_request = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_delete_request.setObjectName("btn_delete_request")
        self.horizontalLayout_4.addWidget(self.btn_delete_request)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 22))
        self.menubar.setObjectName("menubar")
        self.menuConfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEmpresas = QtWidgets.QAction(MainWindow)
        self.actionEmpresas.setObjectName("actionEmpresas")
        self.menuConfiguracion.addAction(self.actionEmpresas)
        self.menubar.addAction(self.menuConfiguracion.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Resultado"))
        self.chk_report.setText(_translate("MainWindow", "Generar Reporte"))
        self.label_2.setText(_translate("MainWindow", "Ubicación del Reporte"))
        self.btn_report.setText(_translate("MainWindow", "Buscar"))
        self.label_3.setText(_translate("MainWindow", "Nombre del Reporte"))
        self.btn_update.setText(_translate("MainWindow", "Actualizar Blacklist"))
        self.label.setText(_translate("MainWindow", "Directorio a consultar"))
        self.btn_folder.setText(_translate("MainWindow", "Buscar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_5.setText(_translate("MainWindow", "Empresa"))
        self.btn_load_empresa.setText(_translate("MainWindow", "Cargar"))
        item = self.tbl_request.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tbl_request.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inicio"))
        item = self.tbl_request.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fin"))
        item = self.tbl_request.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Estado"))
        item = self.tbl_request.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CFDis"))
        item = self.tbl_request.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Estado SAT"))
        item = self.tbl_request.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "id"))
        self.label_6.setText(_translate("MainWindow", "Solicitudes de Descarga Masiva"))
        self.btn_start.setText(_translate("MainWindow", "Iniciar"))
        self.btn_check.setText(_translate("MainWindow", "Verificar"))
        self.btn_download.setText(_translate("MainWindow", "Descargar"))
        self.btn_add_request.setText(_translate("MainWindow", "Agregar"))
        self.btn_delete_request.setText(_translate("MainWindow", "Quitar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuConfiguracion.setTitle(_translate("MainWindow", "Configuracion"))
        self.actionEmpresas.setText(_translate("MainWindow", "Empresas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
