# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'request_packages.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 456)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 50, 481, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tbl_packages = QtWidgets.QTableWidget(self.frame)
        self.tbl_packages.setGeometry(QtCore.QRect(10, 40, 461, 192))
        self.tbl_packages.setObjectName("tbl_packages")
        self.tbl_packages.setColumnCount(3)
        self.tbl_packages.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_packages.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_packages.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_packages.setHorizontalHeaderItem(2, item)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 177, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(170, 250, 128, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 280, 461, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.txt_folder = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_folder.setObjectName("txt_folder")
        self.horizontalLayout_2.addWidget(self.txt_folder)
        self.btn_search = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_2.addWidget(self.btn_search)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 320, 461, 27))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txt_name = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txt_name.setObjectName("txt_name")
        self.horizontalLayout_3.addWidget(self.txt_name)
        self.btn_download = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_download.setObjectName("btn_download")
        self.horizontalLayout_3.addWidget(self.btn_download)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(7, 10, 481, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.select_request = QtWidgets.QComboBox(self.widget)
        self.select_request.setObjectName("select_request")
        self.horizontalLayout.addWidget(self.select_request)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tbl_packages.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UUID"))
        item = self.tbl_packages.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Descargado"))
        item = self.tbl_packages.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "id"))
        self.label_2.setText(_translate("MainWindow", "Paquetes de la Descarga"))
        self.label_5.setText(_translate("MainWindow", "Datos del Archivo"))
        self.label_4.setText(_translate("MainWindow", "Ubicación"))
        self.btn_search.setText(_translate("MainWindow", "Buscar"))
        self.label_3.setText(_translate("MainWindow", "Nombre"))
        self.btn_download.setText(_translate("MainWindow", "Descargar"))
        self.label.setText(_translate("MainWindow", "Solicitud de Descarga"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
